### PR TITLE
Fix naming regarding Rails form naming

### LINKED ISSUE #415: Checkbox spreads over the entire area
Hey,

I created my projects running `rails new my-todo-app --main --css=tailwind` and I created a scaffold model `rails g scaffold Task title:string description:text completed:boolean due_date:datetime` it created a form but checkbox looks weird even this line https://github.com/rails/tailwindcss-rails/blob/main/lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt#L31

it generated this code line in `_form.html.erb`

```
  <div class="my-5">
    <%= form.label :completed %>
    <%= form.checkbox :completed, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
```

Screenshot 2024-10-08 at 14 04 00

I was expecting it wouldn't be cover all width, but it did.

What should I do?

### PR DESCRIPTION
**Pull request by enderahmetyurt**
Fix #415

### CODE REVIEW

File: lib/tailwindcss/version.rb [hunk 1]
```diff
@@ -1,3 +1,3 @@
 module Tailwindcss
-  VERSION = "3.0.0.rc1"
+  VERSION = "3.0.0.rc2"
```
Comment (flavorjones) [inline lib/tailwindcss/version.rb:2]: please don't bump versions in PRs

**Review by flavorjones — APPROVED** [review]
Thank you for opening this PR!

I'm going to edit this PR to remove the version bump, otherwise it looks great. I'll cut a 2.7.8 release with this change in it.

**Comment by flavorjones** [comment]
See https://github.com/rails/tailwindcss-rails/releases/tag/v2.7.8

Thank you again!
